### ISSUE TITLE
Some dll files are missing

### ISSUE THREAD

**Issue by puniaze** [rsmudge/Layer2-Pivoting-Client#1]
Hi Raphael.
I appreciate your research. I have issue about missing wpcap.dll and Packet.dll files. I tried to put those files in same directory as client.exe resides but I got another issue; "Error in pcap_findalldevs: No interfaces found! Make sure libpcap/WinPcap is properly installed on the local machine."
These files are collected from my wireshark and winpcap installed OS , C:\Windows\SysWOW64\ path.
But I didn't get any results.

**Comment by rsmudge** [comment]
You'll want to use the Windows PCAP installer to get this right. You have to drop the right PCAP DLL/SYS files depending on your architecture/OS level. I can't help you troubelshoot this.
